### ISSUE TITLE
Captain Qeez - They have a second spell like

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1222]
https://www.wowhead.com/wotlk/spell=29544/frightening-shout
https://www.wowhead.com/wotlk/npc=15391/captain-qeez#abilities;mode:20player

The second spell of fear is 8 sec, first one is 6 sec.

I remember found some other mobs wich I reported with same behaviour

**Comment by insunaa** [comment]
What this means is that the spell used was gathered by 2 different versions of the wowhead addon: the early wowhead addon which couldn't yet read spell ids from the combatlog, because they weren't there, and a newer wowhead addon which could read spell ids from the combatlog. One of them they name-matched and the other one they got from the newer addon which had the correct spell id. but wowhead never removes old data so the wrong spell that he doesn't have will still remain in wowheads database forever

**Comment by al3xc1985** [comment]
Hmm, and now which might be correct id?

**Comment by insunaa** [comment]
The one we get from sniffs

**Comment by al3xc1985** [comment]
than I can close this one. ty for helping me out
