### ISSUE TITLE
Vekniss Soldier - Missing 1 spell

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1236]
https://www.wowhead.com/wotlk/npc=15229/vekniss-soldier#abilities;mode:40player
https://www.wowhead.com/wotlk/spell=25801/frenzy-aura

**Comment by Grz3s** [comment]
I dont want to be rude or smth, but let me ask You a simple question...
Did you see that creature at all? or its just pure checking every creature from 'x' table in wowhead - and then quick look in EAI... 
Reason why im asking is because he has this aura in `creature_template_addon` .. so you should see it in game.

You created many tickets with very simmilar problems... wonder in how many cases we'll have the same situation

**Comment by al3xc1985** [comment]
U are bot rude, and shall note it down
