### ISSUE TITLE
backport issues

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#182]
today i updated my mangos server. last time i did it -it was pre tbcdb back port
things that not clean:
1) i belive, some quests dissapeared from my quest log
10613 - The Fel and the Furious 
11174- Corrosion Prevention
2) cant find reward from quest [Red Scepter Shard]:
http://wowwiki.wikia.com/wiki/Quest:Nefarius%27s_Corruption
3) my quest log have 2 quests thats was not here before:
http://www.wowhead.com/quest=2882/cuergos-gold
http://www.wowhead.com/quest=11032/protector-no-more

**Comment by Grz3s** [comment]
we not changing anything in characters DB.. so no idea how these things could happened to you.
BUt ok.
Pls remove Cache from your WoW folder
- 10613 - theres no update since 1.1 was released for this quest .. i saw some updates in core for controled units... 
- 11174 - quest was fixed finaly by core update .. so you can go there and redo it again .. should be fine

- [Red Scepter Shard]:
By Powerstream (3,858 – 6·33)  on 2006/11/22 (Patch 1.12.2)   
You have 5 hours before Neffy will destroy the Scepter Shard.

- 2882 was recently chaged to repeatable.. byt why somehow was added into your questlog?? no idea:).. remove it if you dont want it :)
- 11032 nothing was changed there. you can remove it if u dont want it

**Comment by rmzV** [comment]
hello)
last time i updated . it was pre wotlkDB 1.1

the problem not in quests , but in magical replacement:(

[Red Scepter Shard] yes, you have 5 hours to beat Neffy, but when quest done in less then 5 hours. item must be stored in your bag?

**Comment by rmzV** [comment]
11174 - working.

**Comment by Grz3s** [comment]
nothing to fix here
