### ISSUE TITLE
FullDB : spell_template empty

### ISSUE THREAD

**Issue by AliziaKaline** [cmangos/wotlk-db#221]
I just download the last wotlk-db, and after execute "WoTLKDB_1_1_13965.sql" on mangos database, the spell_template table is empty. I don't understand why...

Items, quest, creature, etc... seem okay.

**Comment by evil-at-wow** [comment]
That's normal, and the reason is that the data for the spell_template table isn't in the SQL file you mention (it's maintained as part of the core [here](https://github.com/cmangos/mangos-wotlk/tree/master/sql/base/dbc/original_data)). Actually, you'll be missing a lot more than just spell_template data if you only executed that one Wotlk-DB SQL file...

I would suggest you run the 'InstallFullDB.sh' script, which should be in the root of a typical Wotlk-DB folder (in case you've downloaded only that single SQL file you mention, please download a [release](https://github.com/cmangos/wotlk-db/releases) instead). The first time you run the script, it will create a small configuration file and it will ask you to edit the generated file to fill in some info (like the hostname/IP of the SQL server to connect to, the name of the database, etc). Once you've done that, the script takes care of applying everything (= lots of SQL files) in the correct order.

**Comment by Grz3s** [comment]
because spell_template is not part of DB anymore... it has to be added separately...

this note you should see there: https://github.com/cmangos/wotlk-db/releases
```quote
IMPORTANT
 Pls: Rerun ./InstallFuLLDB.sh Tool (req. for Spell_templates - or add
 them manually)
```


So if you want to do it without provided tool... You need to add all step by step

1st. you need to add everything whats \mangos-wotlk\sql\base\dbc
 \\original_data\ <--- (this must goes first)
 \\cmangos_fixes\
2nd. Also ACID need to be added if you want to see creatures using spells etc.
\\wotlk-db\ACID\acid_wotlk.sql

Following Ours installation instructions .. all that hassle will be done automatically for You.
https://github.com/cmangos/wotlk-db#installation

P.S. /InstallFullDB.sh  Tool is very easy to use

**Comment by Grz3s** [comment]
wanted to explain also... but .. @evil-at-wow did it quicker :)...
Anyway nothing to fix here ..closed

**Comment by AliziaKaline** [comment]
Sorry but InstallFullDB.sh don't work :/ Nothing happen.

![image](https://user-images.githubusercontent.com/12145066/34963714-4db07c16-fa4a-11e7-8d4a-20d7d6674c2c.png)

(I don't understand the error message... I have the last DB and core, no way to up-to-date it more)

I edited config correctly, with and without optional core path, same result.

Did you try to reinstall the last DB and the last core ?

**Comment by killerwife** [comment]
CORE_DIR variable in installscript has to be set correctly.

**Comment by AliziaKaline** [comment]
CORE_PATH ? I did it. Same error.

**Comment by killerwife** [comment]
also your image didnt show error message, its a timer for 10 seconds and then it starts

**Comment by AliziaKaline** [comment]
But it does nothing. It wait 10s and close itself.

**Comment by killerwife** [comment]
open it in command line (git bash) and see the error.

**Comment by AliziaKaline** [comment]
"ERROR: cannot apply Full_DB/WoTLKDB_1_1_13965.sql"

**Comment by Grz3s** [comment]
To access the mysql command in Windows without manually changing changing directories, do this:
•Go to Control Panel > System > Advanced system settings.
•System Properties will appear.
•Click on the 'Advanced' tab.
•Click 'Environment Variables'.
•Under System Variables, locate 'Path' and click Edit.
•Append the path to your MySQL installation to the end of the exisiting 'Variable value'. Example:
;C:\Program Files\MySQL\MySQL Server 5.5\bin;

**Comment by AliziaKaline** [comment]
It's working. Thanks you !
