### ISSUE TITLE
baron rivendale

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#386]
after killing rammstein, group of ghouls come
later doors opened and guardians come out after that doors get closed.
how too enter?)

**Comment by insunaa** [comment]
That's an issue in the core, not the database.

**Comment by rmzV** [comment]
@insunaa i am agreed on your statement, but requirements for posting bugs in issues place are way time consuming,
i this branch i just wrote  2 strings with explanation what happens and in issues ..thats like entire quest for me))

**Comment by insunaa** [comment]
@rmzV yeah, and for exactly that reason I won't fix it...
maybe some other dev will, tho :)

**Comment by rmzV** [comment]
@insunaa may be:) .. but, i believe that they prefer to have bugs in code due to wrong ticket fulfillment, than fix something.
like example:
https://github.com/cmangos/issues/issues/1917

**Comment by insunaa** [comment]
@rmzV Nobody here is getting paid... There is no "wrong ticket fulfillment"... People fix the bugs they care about, and when people who report bugs intentionally don't use the templates given, or post them in the wrong places it means that the devs have to work harder for absolutely no reason.

*You* have an issue that you need fixed, you can either fix it yourself, or you can at least try to help the devs with fixing it, by using the template in the correct place for reporting issues, so that devs can concentrate on fixing problems, not on herding cats.

**Comment by rmzV** [comment]
@insunaa, lets just hope, that some one maybe find this bug again... maybe write proper ticket.. maybe someone decided to fix it:)

**Comment by miraco** [comment]
The problem about reports like this, is that the dev has to do all the research about the bug and that’s really time consuming.

**Comment by rmzV** [comment]
okey what exactly information required and not preserved?

**Comment by miraco** [comment]
Maybe some ids, like gobject id/guid from the door  or npcs 
You say door after killing some npc don’t open and you expect that every dev in here knows what npc or what door you mean. 
then an Proof that what you say is buged and a proof that shows us how it should work.

there is s reason cmangos have issue template.. 

If you want things to get fixed, either fix it your self or do proper bug reports

**Comment by rmzV** [comment]
okey!
but may we have a compromise, for already created tickets?
 if the bug report is not proper fulfilled? (is that correct word?) can it be not closed like that and left "as is" untill someone decided to fix it?

i have only 3 tickets that are core issues
https://github.com/cmangos/issues/issues/1917
https://github.com/cmangos/issues/issues/2442
and this one
https://github.com/cmangos/wotlk-db/issues/386

once more: my goals: find every possible bug and report it. To fix or not to fix will be always up to developers. 
But closing created tickets - > not looks like a friendly move.

**Comment by insunaa** [comment]
If you make an attempt at a detailed ticket with the information requested by the template, as re-iterated by miraco, nobody will close the ticket unsolved, unless it turns out that the issue isn't a bug but intended behavior for example.

It's appreciated that you try to find bugs, but if you're not properly communicating these bugs by stating the required information, you're making the bugs harder to fix, than if you were stating the requested contextual information.
