### ISSUE TITLE
The Binding

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#411]
https://www.wowhead.com/quest=1504/the-binding

//may be wrong quest ID, but it doesnot work
VW doesnot summoning(

**Comment by rmzV** [comment]
still doesnot work

**Comment by Grz3s** [comment]
![dddu](https://user-images.githubusercontent.com/2374069/174187198-0c578bfc-8e41-4ac6-a8df-4a3004f43a44.jpg)
just tested it with fresh lvl 10 char... and it works perfect...
pls give me more details what happens?

**Comment by rmzV** [comment]
Hmm, i tested it with BE and it works, but Undead summoning in Undercity doesnot(

**Comment by Grz3s** [comment]
Theyre diff quests for each race.. and diff places they are happening...
https://tbc.wowhead.com/quest=9619/the-rune-of-summoning -- Blood Elf only
https://tbc.wowhead.com/quest=1471/the-binding - Undead Only
https://tbc.wowhead.com/quest=1504/the-binding - Orc Only
You should say that issue is about 1471 instead of this one...

**Comment by Grz3s** [comment]
all 3 rechecked .. should be fine now
