### ISSUE TITLE
Enchanted Thorium

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#469]
https://classic.wowhead.com/spell=17180/enchanted-thorium

enchanters spell
now blacksmith can learn it too

**Comment by Grz3s** [comment]
![dnwqd](https://user-images.githubusercontent.com/2374069/195191593-3e9fd8da-c99c-4a1b-b635-d632d542bd00.jpg)

```now blacksmith can learn it too``` ?

**Comment by rmzV** [comment]
my bad
https://dropmefiles.com/H0TXY

its "mining"trainer

**Comment by Grz3s** [comment]
I still dont understand what actual issue is?
So lets establish few facts:
 - `(Patch 3.3.0)
Visited the mining trainer just for the heck of it and found, to my surprise, that he now taught how to make Enchanted Thorium just as enchanters used to do. I never recall seeing this before so I assume it's new for miners in 3.3. Requires a min skill of 250.
`
source:
https://www.wowhead.com/wotlk/spell=70524/enchanted-thorium#comments

- i checked Makaru (guy from your pic) on wotlkDB..and he teaches this - which is correct.

So everything seems to be correct on our end. 
Im going to close it.. Feel free to comment if smth else is needed here.
