### ISSUE TITLE
Missing Tzerak spawn script

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#601]
- [ ] https://www.youtube.com/watch?v=i47EARvEJO0&t=19s

In the movie u can see how Tzerak is spawned by 4 or 6 Nazzivus Summoners.
After he is spawned he does a fire spell or something alike, that kills his summoners

Also a few more comments about his summoning/respawning/despawning info can be found here
https://www.wowhead.com/tbc/npc=17528/tzerak#comments

Also I found the yell that he uses when he spawns

![image](https://github.com/cmangos/wotlk-db/assets/6240049/4f0d10ca-191c-419d-8012-434545408483)

https://www.wowhead.com/tbc/npc=17524/nazzivus-summoner
in the screen shot u can see the summoner using a beam spell, used in summoning Tzerak.
Also in the movie the summoners have that casting green thing all the time

- [ ] In the movie u also see in the left side a summoner permanently spawned in the left side, that stands there. On the current implementation we do not have that summoner spawned
- [ ] Also this mob should have random movement added, he currently stands

![image](https://github.com/cmangos/wotlk-db/assets/6240049/e04366e7-d300-456f-8d84-d29f6e7cdc68)

**Comment by Grz3s** [comment]
smth interesting ...

**Comment by Grz3s** [comment]
`By 169839) 2009/08/21] (Patch 3.2.0)
It doesn't matter if you kill every demon of none of the demons, he will continue to run on his 6 minute cycle. If someone does kill him, he will respawn at the summoning circle 2 minutes later, however, he has not been summoned by demons since patch 3.0. He just respawns there like any other mob.`


This is exact what happens in wotlkClassic , retail.. and WoTLKDB.

Funny that he still Yells ... (we got that also).
